export { htmlEscape, htmlEscapeMultiline } from './escape.js'
export { resolveMailBrand, MAIL_SITE_NAME, MAIL_COLORS, MAIL_LOGO_PATH } from './tokens.js'
export type { MailBrandContext } from './tokens.js'
export { renderMail } from './render.js'
export type { MailTemplateKind, MailTemplateVarsMap } from './render.js'
export { MAIL_TEST_SUBJECT } from './kinds/mailTest.js'
